- name: Create FRR Shared Folder on Host
  file: path=/root/frr state=directory mode=0755


# The FRR daemons file is a static file that specifies which subdaemons
# are actually running (zebra, bgpd, ospf). This file is not required when
# FRR is being run using systemd.
#- name: configure FRR daemons file
#  copy: src=daemons dest=/root/frr/daemons

# This writes configuration to the FRR configuration file using the
# information in group_vars/all. The biggest difference between spine and
# leaf configuration are the prefix lists - leafs should only advertise their
# neighboring networks, but spines should advertise any networks they accept.
# The 'leaf' variable handles this logic for us in our template.
- name: Render a FRR Config for the RoH Container
  template: src=frr.conf.j2 dest=/root/frr/frr.conf

- name: Deploy RoH Container
  docker_container:
    name: cumulus-roh
    privileged: true
    interactive: true
    network_mode: host
    restart_policy: unless-stopped
    tty: true
    recreate: yes
    image: cumulusnetworks/frrouting:latest
    volumes:
      - "/root/frr/frr.conf:/etc/frr/frr.conf"

- name: Deploy CRoHDAd Container
  docker_container:
    name: crohdad
    privileged: true
    interactive: true
    network_mode: host
    restart_policy: unless-stopped
    tty: true
    recreate: yes
    image: cumulusnetworks/crohdad:1.0.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/iproute2/rt_tables:/etc/iproute2/rt_tables"
      - "/dev/log:/dev/log"

- name: Create a network with options
  docker_network:
    name: "{{interfaces[inventory_hostname].docker_network}}"
    driver_options:
      com.docker.network.bridge.name: "{{docker_networks[interfaces[inventory_hostname].docker_network].bridge_name}}"
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'false'
      com.docker.network.driver.mtu: '9216'
    ipam_options:
      subnet: "{{docker_networks[interfaces[inventory_hostname].docker_network].subnet}}"
      gateway: "{{docker_networks[interfaces[inventory_hostname].docker_network].gateway}}"

- name: Enable Proxy Arp on Newly Created Docker-Bridge
  sysctl:
    name: "net.ipv4.conf.{{docker_networks[interfaces[inventory_hostname].docker_network].bridge_name}}.proxy_arp"
    value: 1
    state: present

