- name: Install Docker Repo's Public Key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add Docker Sources (HTTPS)
  lineinfile:
    create: yes
    dest: /etc/apt/sources.list.d/docker.list
    line: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'

- name: Install Docker, Ifupdown2 and PIP
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - docker-engine
    - python-pip

- name: Install IFUPDOWN2
  apt: name=ifupdown2 state=installed update_cache=yes
  when: inventory_hostname != "oob-mgmt-server"

- name: Add Docker-py Module
  pip: name=docker-py

- name: Allow IfUpdown2 to Run at Boot
  lineinfile:
    dest: "/lib/systemd/system/networking.service"
    regexp: '^RemainAfterExit'
    insertafter: '^\[Service\]'
    line: 'RemainAfterExit=yes'
  when: inventory_hostname != "oob-mgmt-server"

- name: Start the Docker Daemon (if it isn't already running)
  service: name=docker state=started


- block:
    - name: Pull Containers to oob-mgmt-server
      docker_image:
        name: "{{item}}"
      with_items:
        - "cumulusnetworks/quagga:latest"
        - "cumulusnetworks/crohdad:latest"

    - name: Save Containers to Web Dir on oob-mgmt-server
      shell: docker save -o /var/www/html/{{item}}.tar cumulusnetworks/{{item}}:latest
      with_items:
        - "quagga"
        - "crohdad"

    - name: Fixing File Permissions to Allow Container Download
      file:
        path: /var/www/html/{{item}}.tar
        mode: 0755
      with_items:
        - "quagga"
        - "crohdad"

  when: inventory_hostname == "oob-mgmt-server"
